# Generated by Django 4.2.2 on 2025-01-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="soft_delete",
            field=models.BooleanField(default=False, verbose_name="Delete User"),
        ),
    ]
