# Generated by Django 4.2.2 on 2025-01-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0003_alter_image_alt_text_alter_image_name"),
        ("Contents", "0003_alter_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                related_name="image_post",
                through="Contents.PostImage",
                to="Core.image",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="tag_post",
                through="Contents.PostTag",
                to="Contents.tag",
                verbose_name="تگ",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(verbose_name="متن"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=100, verbose_name="عنوان"),
        ),
    ]
