# Generated by Django 4.2.2 on 2025-01-21 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Contents", "0004_alter_post_images_alter_post_tags_alter_post_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Follow_Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "follower_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Follower_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Following_Tag",
                        to="Contents.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Follow Tag",
                "verbose_name_plural": "Follow Tags",
            },
        ),
    ]
