# Generated by Django 4.2.2 on 2025-01-23 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Contents", "0006_alter_follow_tag_unique_together_archive"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archive",
            name="create_at",
        ),
        migrations.RemoveField(
            model_name="archive",
            name="update_at",
        ),
        migrations.RemoveField(
            model_name="archive",
            name="user",
        ),
        migrations.AddField(
            model_name="archive",
            name="archiver_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_archive",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive",
                to="Contents.post",
            ),
        ),
    ]
