# Generated by Django 4.2.2 on 2025-01-23 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Contents", "0007_remove_archive_create_at_remove_archive_update_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="archiver_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_archive",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
