# Generated by Django 4.2.2 on 2025-01-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Contents", "0009_alter_archive_archiver_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive",
                to="Contents.post",
            ),
        ),
    ]
