# Generated by Django 4.2.2 on 2025-01-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Contents", "0010_alter_archive_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="soft_delete",
            field=models.BooleanField(default=False, verbose_name="Delete Post"),
        ),
    ]
