# Generated by Django 4.2.2 on 2025-01-09 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Alternative Text"
                    ),
                ),
                ("model_name", models.CharField(max_length=50)),
                (
                    "Image",
                    models.ImageField(
                        upload_to="images/%(model_name)s/", verbose_name="Image"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
    ]
