# Generated by Django 4.2.2 on 2025-01-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0002_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="alt_text",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Alternative Text"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Name"
            ),
        ),
    ]
